;Size:242
                      
;********************************
; C:\Work\Patrick's Project\scripts\REGIONS\WEAVE\COREENTRANCE\MAP01\WVECOREENTRANCE01.s
;********************************
;	Author:	MGI PARSE
;	(c)2000	Interactive Imagination
;	All rights reserved

;********************************
?_WVECOREENTRANCE01_DR_1
	DB	CMD_THATACTORINIT
		DB	(((ACTOR01-ACTOR_RAM)/ACTOR_STRUCT_SIZE)&$FF)
		DW	(?TRIGGER_AI&$FFFF)
		DB	$16
		DB	$25
		DW	$D956
		DB	$10
		DB	:?_OVERPARA_WAIT
		DW	(?_OVERPARA_WAIT&$FFFF)
		DB	:?_OVERPARA_MOUNT
		DW	(?_OVERPARA_MOUNT&$FFFF)

	DB	CMD_HEROSETDOOR
		DB	$06
		DB	$29

	DB	CMD_JUMP
		DB	:?_OVRSURFACE01
		DW	(?_OVRSURFACE01&$FFFF)

;********************************
?_WVECOREENTRANCE01_DR_2
	DB	CMD_HEROSETDOOR
		DB	$17
		DB	$06

	DB	CMD_JUMP
		DB	:?_CREGATE01
		DW	(?_CREGATE01&$FFFF)

;********************************
?_WVECOREENTRANCE01_FADEIN
	DB	CMD_FADEOUTSONG
		DB	$1E

	DB	CMD_SCENENEW

	DB	CMD_LOADMAP
		DW	(MAP_WVECOREENTRANCE01&$FFFF)
		DB	:MAP_WVECOREENTRANCE01

	DB	CMD_LOADPALETTE
		DW	(PAL_HERO&$FFFF)
		DB	:PAL_HERO

	DB	CMD_PALCLEARANIM
		DB	$07
		DW	$7FFF

	DB	CMD_JUMP
		DB	:?_WVECOREENTRANCE01_GENERIC
		DW	(?_WVECOREENTRANCE01_GENERIC&$FFFF)

;********************************
?_WVECOREENTRANCE01
	DB	CMD_SCENENEW

	DB	CMD_LOADMAP
		DW	(MAP_WVECOREENTRANCE01&$FFFF)
		DB	:MAP_WVECOREENTRANCE01

	DB	CMD_LOADPALETTE
		DW	(PAL_HERO&$FFFF)
		DB	:PAL_HERO

;********************************
?_WVECOREENTRANCE01_GENERIC
	DB	CMD_SETXRAMBYTE
		DW	(XRAM_SAVEVARS+$008E)
		DB	$01

	DB	CMD_LOADHOTSPOTS
		DW	(HS_WVECOREENTRANCE01&$FFFF)

	DB	CMD_SETITEMSCRIPT
		DB	:_DEAL
		DW	(_DEAL&$FFFF)

	DB	CMD_THATACTORINIT
		DB	(((HEROACTOR-ACTOR_RAM)/ACTOR_STRUCT_SIZE)&$FF)
		DW	(?HERO_AI&$FFFF)
		DB	$05
		DB	$05
		DW	$D0CD
		DB	$00
		DB	:?_HERO_STANDL_ANIM
		DW	(?_HERO_STANDL_ANIM&$FFFF)
		DB	:?_DONT_TALK
		DW	(?_DONT_TALK&$FFFF)

	DB	CMD_THATACTORSTART
		DB	(((HEROACTOR-ACTOR_RAM)/ACTOR_STRUCT_SIZE)&$FF)

	DB	CMD_HEROFROMDOOR

	DB	CMD_HEROSETCAMERA

	DB	CMD_SCENEREADY

	DB	CMD_PALFADE
		DB	$20
		DB	$07

	DB	CMD_SONGSTART
		DB	SONGID_destruction

	DB	CMD_END

;********************************
_DEAL
	DB	CMD_IF
		DB	EXPR_NOTEQU
		DB	EXPR_XRAMBYTE
		DW	(SCRIPT_COLLISION_CODE+$0000)&$FFFF
		DB	EXPR_WORDCONST
		DW	COLLCODE_ITEM01
		DB	:?_TXT_NOTHING_HAPPENED
		DW	(?_TXT_NOTHING_HAPPENED&$FFFF)

	DB	CMD_SWITCH
		DB	EXPR_XRAMBYTE
		DW	(SCRIPT_USED_ID+$0000)&$FFFF
		DB	:_COIN
		DW	INV_3_HEADEDCOIN
		DW	(_COIN&$FFFF)
		DB	:_SCALE
		DW	INV_BALANCESCALE
		DW	(_SCALE&$FFFF)
		DB	:_PLOD
		DW	INV_PLOD_SPNEW
		DW	(_PLOD&$FFFF)
		DB	:_BUCKET
		DW	INV_BUCKETOPINK
		DW	(_BUCKET&$FFFF)
		DB	$FF

;********************************
_COIN
	DB	CMD_IF
		DB	EXPR_XRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)&$FFFF
		DB	:_DONE
		DW	(_DONE&$FFFF)

	DB	CMD_SETXRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)
		DB	$01

	DB	CMD_JUMP
		DB	:?_TXT_NOTHING_HAPPENED
		DW	(?_TXT_NOTHING_HAPPENED&$FFFF)

;********************************
_SCALE
	DB	CMD_IF
		DB	EXPR_NOTEQU
		DB	EXPR_XRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)&$FFFF
		DB	EXPR_BYTECONST,$01
		DB	:_DONE
		DW	(_DONE&$FFFF)

	DB	CMD_SETXRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)
		DB	$02

	DB	CMD_JUMP
		DB	:?_TXT_NOTHING_HAPPENED
		DW	(?_TXT_NOTHING_HAPPENED&$FFFF)

;********************************
_PLOD
	DB	CMD_IF
		DB	EXPR_NOTEQU
		DB	EXPR_XRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)&$FFFF
		DB	EXPR_BYTECONST,$02
		DB	:_DONE
		DW	(_DONE&$FFFF)

	DB	CMD_SETXRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)
		DB	$03

	DB	CMD_JUMP
		DB	:?_TXT_NOTHING_HAPPENED
		DW	(?_TXT_NOTHING_HAPPENED&$FFFF)

;********************************
_BUCKET
	DB	CMD_IF
		DB	EXPR_NOTEQU
		DB	EXPR_XRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)&$FFFF
		DB	EXPR_BYTECONST,$03
		DB	:_DONE
		DW	(_DONE&$FFFF)

	DB	CMD_SETXRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)
		DB	$00


	DB	CMD_TEXTICON
		DW	ICON_POLLY

	DB	CMD_TEXTWRITE
		DB	(?AL+$00),(?AL+$05),(?0+$06),(?AL+$04),(?0+$03),(?0+$07),(?AL+$16),(?AL+$01),(?AL+$0E),(?AL+$0B),(?0+$00),(?0+$09),(?AL+$04),(?AL+$11),(?AL+$16),?HURRY
		DB	(?0+$02),(?0+$03),(?AL+$0A),(?AL+$04),(?AL+$0B),(?AL+$05),(?AL+$08),(?0+$08),(?0+$06),(?0+$05),(?AL+$11),(?AL+$04),(?AL+$02),(?0+$01),(?0+$02),?WAIT
		DB	?EOF

	DB	CMD_TEXTCLOSE

	DB	CMD_END

;********************************
_DONE
	DB	CMD_SETXRAMBYTE
		DW	(XRAM_SAVEVARS+$0097)
		DB	$00

	DB	CMD_JUMP
		DB	:?_TXT_NOTHING_HAPPENED
		DW	(?_TXT_NOTHING_HAPPENED&$FFFF)

;********************************
; 	GLOBALS
;********************************
	GLOBAL	ACTOR01
	GLOBAL	ACTOR_RAM
	GLOBAL	?TRIGGER_AI
	GLOBAL	?_OVERPARA_WAIT
	GLOBAL	?_OVERPARA_MOUNT
	GLOBAL	?_OVRSURFACE01
	GLOBAL	?_CREGATE01
	GLOBAL	MAP_WVECOREENTRANCE01
	GLOBAL	PAL_HERO
	GLOBAL	XRAM_SAVEVARS
	GLOBAL	HS_WVECOREENTRANCE01
	GLOBAL	HEROACTOR
	GLOBAL	?HERO_AI
	GLOBAL	?_HERO_STANDL_ANIM
	GLOBAL	?_DONT_TALK
	GLOBAL	SCRIPT_COLLISION_CODE
	GLOBAL	?_TXT_NOTHING_HAPPENED
	GLOBAL	SCRIPT_USED_ID

;********************************
	END
;********************************